name: Forward PR

on:
  pull_request:
    types:
      - opened

jobs:
  transfer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Forward
        uses: ./.github/actions/forward
        with:
          src_token: ${{ secrets.GITHUB_TOKEN }}
          dest_token: ${{ secrets.GITLAB_TOKEN }}
          dest_repo: "gitlab.com/tagoh/forward-test"
          title: ${{ github.event.pull_request.title }}
          body: ${{ github.event.pull_request.body }}
          url: ${{ github.event.pull_request.html_url }}
          patch: ${{ github.event.pull_request.patch_url }}
          reporter: ${{ github.event.pull_request.user.login }}
